#!/bin/bash

if ! [ -e ".done" ]; then
	echo "Nothing to undo."
	exit 1
fi

make clean

if [ `uname` = "Darwin" ] || [ `uname` = "FreeBSD" ]; then
	mv src/Makefile src/Makefile.bsd
	mv src/Makefile.old src/Makefile
elif [ `uname` = "Linux" ]; then
	mv src/Makefile src/Makefile.linux
	mv src/Makefile.old src/Makefile
fi

rm -f .compiler
rm -f .ecflags
rm -f .elflags
rm -f .done

exit 0
