#!/bin/sh

if ! [ -e ".done" ]; then
	echo "Nothing to undo."
	exit 1
fi

make clean

cp src/Makefile.old src/Makefile
rm -f src/Makefile.old

rm -f .compiler
rm -f .target
rm -f .archflags
rm -f .ecflags
rm -f .elflags
rm -f .done

exit 0
